# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.2.0
   hooks:
   -   id: trailing-whitespace
   -   id: end-of-file-fixer
   -   id: check-yaml
   -   id: check-added-large-files
  # djlint
-  repo: https://github.com/djlint/djLint
   rev: v1.36.4
   hooks:
   -  id: djlint-reformat-jinja
      files: "\\.html"
      types_or: ["html"]
   #-  id: djlint-jinja
      #files: "\\.html"
      #types_or: ["html"]
   # black
-  repo: https://github.com/psf/black
   rev: 22.10.0
   hooks:
   -   id: black
#- repo: https://github.com/eslint/eslint
  #rev: v8.57.0 # Use a recent stable version of ESLint
  #hooks:
  #-   id: eslint
      #files: \.(js|jsx|ts|tsx)$ # Target JavaScript, JSX, TypeScript, and TSX files
      #args: [--fix] # Optional: automatically fix linting issues
